version: 1.0.{build}.0

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: Wav.Net\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '1.0.0-beta'

build:
  project: ./Wav.Net/Wav.Net.sln
  parallel: true
  verbosity: minimal

after_tests:
- ps: .\NuGet\pack.ps1

artifacts:
- path: Wav.Net\bin\Release\Wav.Net.dll
  name: Wav.Net.dll
- path: '**\Wav.Net*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
