version: 1.0.0.{build}

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: Wav.Net\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '1.0.0-beta'

before_build:
- nuget restore

build:
  project: Wav.Net.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: .\NuGet\pack.ps1
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
